### ISSUE TITLE
-k option may not working

### ISSUE THREAD

**Issue by komuro-hiraku** [s-fujimoto/sshec2#10]
I want to access EC2 instance with my SSH private key. But may not work.

## Environment

- macOS: 10.12.6
- sshec2 (0.1.10)
- Python: Python 3.6.1

```
sshec2 -k .ssh/private.pem --debug
Traceback (most recent call last):
  File "/Users/komurohiraku/.pyenv/versions/3.6.1/bin/sshec2", line 5, in <module>
    sshec2.sshec2.main()
  File "/Users/komurohiraku/.pyenv/versions/3.6.1/lib/python3.6/site-packages/sshec2/sshec2.py", line 201, in main
    instances = describe_instances(args.profile, args.region)
  File "/Users/komurohiraku/.pyenv/versions/3.6.1/lib/python3.6/site-packages/sshec2/sshec2.py", line 56, in describe_instances
    result = ec2.describe_instances(Filters=[{'Name': 'instance-state-code', 'Values': ['16']}])
  File "/Users/komurohiraku/.pyenv/versions/3.6.1/lib/python3.6/site-packages/botocore/client.py", line 253, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/komurohiraku/.pyenv/versions/3.6.1/lib/python3.6/site-packages/botocore/client.py", line 557, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AuthFailure) when calling the DescribeInstances operation: AWS was not able to validate the provided access credentials
```

Try with other option. -r, -u, but not works too.

```
sshec2 -k .ssh/private.pem -r ap-northeast-1 -u ec2-user --debug
```

What's wrong?

Thanks

**Comment by s-fujimoto** [comment]
```
AWS was not able to validate the provided access credentials
```

This message is a invalid access key in IAM user. You check following...

- Check ```aws_access_key_id``` and ```aws_secret_access_key``` of default profile in ```$HOME/.aws/profile```.
- Check to disable access key in IAM user.

**Comment by komuro-hiraku** [comment]
Thank you for your quick advice.

checked my credentials. Result, My default profile set dummy credentials. So I tried choose correct profile with -p option and -k option.

Results, It works below command

```
sshec2 -k .ssh/private.pem -p my_profile 
[ SELECT TARGET INSTANCE LIST ]
  0: xxxxxxx (i-xxxxxxx) ap-northeast-1c
  1: 
....
```

Thank you.
